sut(muzluSut)
sut(vanilyaliSut)
sut(cilekliluSut)
sut(karamelliluSut)
sut(cikolataliluSut)

marka(eti)
sut(ulker)
sut(torku)
sut(oreo)
sut(milka)

kurabiyeCesit(cikolataParcali)
kurabiyeCesit(sutlu)
kurabiyeCesit(vanilyali)
kurabiyeCesit(tarcinli)
kurabiyeCesit(kakaolu)

ortam(koltuk)
ortam(cekyat)
ortam(hali)
ortam(dolap)
ortam(masa)

kutuRenk(sari)
kutuRenk(mor)
kutuRenk(kirmizi)
kutuRenk(kahverengi)
kutuRenk(mavi)

isim(fatma)
isim(ayse)
isim(ali)
isim(ahmet)
isim(deniz)